services:

  web:
    build:
      context: .
    container_name: web-app
    command: /bin/bash "/app/entrypoint.sh"
    env_file: .env
    ports:
      - "8000:8000" # default port for Django.. the only one we need to expose to access the app from the host machine browser
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    
  db:
    image: postgres:latest
    container_name: db-app
    env_file: .env
    # ports:
    #   - "5432:5432" # default port for postgres.. no need to expose it here..
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    container_name: redis-app
    # ports:
      # - "6379:6379" # ..it seems that the school runs REDIS on this port...
      # - "6380:6379"

volumes:
  postgres_data:
